In [1]:
import numpy as np
m = np.array(([5,6,7,87,9],[3,4,5,6,7],[2,2,90,-1,2]), dtype= np.int32)
m.ndim
m.shape
m.flags #c contigous: row major, fortran contigous column major


  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [2]:
m.strides

(20, 4)

In [3]:
m = np.array(([5,6,7,87,9],[3,4,5,6,7],[2,2,90,-1,2]), dtype= np.int64)  #change dtype ans see how strid3es chnage
m.strides
#strides (a,b) in row major says, u need a bytes to go to next row and b bytes to go to next element of row

(40, 8)

In [4]:
# NumPy, strides provide metadata about how to access the data in memory,
# but they do not represent the physical memory locations of the data elements or data itself.

#what is stride: Strides are a tuple of integers that tell you the number of bytes you need to move to get from one element to the next along each dimension

#strides do not change the actual data; they only change how you access the data. basically view

arr = np.arange(6)
print(arr)
print(arr.flags)
print(arr.strides)

arr_new = arr.reshape(2,3)
print(arr is arr_new)   #Since this is a new reshaped view, it shares the same data as arr, but does not point to the exact same memory address. so diff
print(arr_new.flags)

arr_new[0,0] = 999  #it changes in original one also

print(arr_new)
print(arr)      
# print(id(arr))
# print(id(arr_new))



[0 1 2 3 4 5]
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

(4,)
False
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

[[999   1   2]
 [  3   4   5]]
[999   1   2   3   4   5]


In [5]:
arr[1] = 89

print(arr)
print(arr_new)

# When we reshape , only strides change and it creates a view, underlying memeory architecure remains same
# When we reshape an array in NumPy, the physical memory of the underlying data does not change; only the logical view of the data changes.
# This is why the strides change but the underlying memory remains the same.

print(arr.strides)
print(arr_new.strides)

[999  89   2   3   4   5]
[[999  89   2]
 [  3   4   5]]
(4,)
(12, 4)


In [6]:
thre = np.arange(3*3*3)
th = thre.reshape(3,3,3)
print(th)
print(thre.flags)
print(thre.strides)

print(th.strides)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

(4,)
(36, 12, 4)


In [7]:
# The difference between shallow and deep copying is only relevant for compound objects (objects that contain other objects, like lists or class instances):

# A shallow copy constructs a new compound object and then (to the extent possible) inserts references into it to the objects found in the original.

# A deep copy constructs a new compound object and then, recursively, inserts copies into it of the objects found in the original.

import copy
ab = [[1,2,3],[2,2,2]]
cd = copy.copy(ab) #shallow copy   #useful if we are working with immutable data
bd = copy.deepcopy(ab)  #deepcopy


print(ab is cd)          #false
print(ab[0] is cd[0])     #true

print(ab is bd)
print(ab[0] is bd[0])

False
True
False
False


In [8]:
b = np.arange(4*5).reshape(4,5)
print(b)
print(b[1,])
print(b[:,1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[5 6 7 8 9]
[ 1  6 11 16]


In [9]:
b[:,2:4]

array([[ 2,  3],
       [ 7,  8],
       [12, 13],
       [17, 18]])

In [10]:
b[::2,::2]

array([[ 0,  2,  4],
       [10, 12, 14]])

In [11]:
print(th)
print(th.shape)
print("\n after indexing")
print(th[0:,0:,::2])
print(th[0:,0:,::2].shape)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
(3, 3, 3)

 after indexing
[[[ 0  2]
  [ 3  5]
  [ 6  8]]

 [[ 9 11]
  [12 14]
  [15 17]]

 [[18 20]
  [21 23]
  [24 26]]]
(3, 3, 2)


In [12]:
print(th[...,2])  #ellipse, its quyivalent to th[:,:,2] bvetter if we have 100 dim array
th[2,...]

[[ 2  5  8]
 [11 14 17]
 [20 23 26]]


array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [13]:
#boolean indexing
#suppose u are working with financial data
data = np.array([100,20,40,400,65,18,26,99,32,29])
condition = data > 50
print(condition)
x = data[condition]
x

[ True False False  True  True False False  True False False]


array([100, 400,  65,  99])

In [14]:
#structured datatpes