In [1]:
import numpy as np

#advanced indexing: Advanced indexing is triggered when the selection object, obj, is a non-tuple sequence object,
#  an ndarray (of data type integer or bool), or a tuple with at least one sequence object or ndarray (of data type integer or bool).
#  There are two types of advanced indexing: integer and Boolean.


#Advanced indexing always returns a copy of the data (contrast with basic slicing that returns a view).

x = np.array([10,  9,  8,  7,  6,  5,  4,  3,  2])
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [2]:
ab = np.array([[9,9,9,9],[8,88,8,8],[7,7,7,7]])
t = ab[1:3]   #BASIC SLICING
print(t)
print(ab)
t.flags

[[ 8 88  8  8]
 [ 7  7  7  7]]
[[ 9  9  9  9]
 [ 8 88  8  8]
 [ 7  7  7  7]]


  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [3]:
loo = ab[2]
print(loo)   #no owndata thats why its a view
loo.flags

[7 7 7 7]


  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [4]:
ho = ab[np.array([2])]
print(ho)
ho.flags     #copy because own data

[[7 7 7 7]]


  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [5]:
x[np.array([4,4,4,4,-1,0])]

array([ 6,  6,  6,  6,  2, 10])

In [6]:
x = np.array([[1, 2], [3, 4], [5, 6]])
print("original =" , x)
x[[0,1,2],[1,0,1]]  #will output (0,1) = 2, (1,0) = 3, (2,1) = 6

original = [[1 2]
 [3 4]
 [5 6]]


array([2, 3, 6])

In [7]:
# From a 4x3 array the corner elements should be selected using advanced indexing.
# Thus all elements for which the column is one of [0, 2] and the row is one of [0, 3] need to be selected.

x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
x.shape
x.ndim

rows = np.array([[0,0],
                 [3,3]])

#print(x[rows])

col = np.array([[0,2],[0,2]])

# rows = np.array([0,0,3,3])   #output will be edge elements but in form of 1 d array array([ 0,  2,  9, 11])
# col = np.array([0,2,0,2])

x[rows,col]




array([[ 0,  2],
       [ 9, 11]])

In [8]:

#The function np.ix_ in NumPy is called the "indexer function" or "indexing function for broadcasting."$
x[[0,3],[0,2]] # array([ 0, 11])
x[np.ix_([0,3],[0,2])]

array([[ 0,  2],
       [ 9, 11]])

In [9]:
# This is a great example of how advanced indexing with NumPy can be applied in a real-world scenario. Here's how it can be implemented:

# Scenario: Color Lookup Table for an Image
# Imagine you have:

# A grayscale image (2D array) where each pixel contains an integer value representing a grayscale intensity.
# A color lookup table (LUT), which maps these grayscale intensities to RGB color values.
# Using advanced indexing, you can map the grayscale values of the image to their corresponding RGB values, producing a colorized image.

# Grayscale image (2D array)


# image = np.array([[0, 1, 2,1],
#                   [2, 1, 0,1],
#                   [1, 0, 2,1]], dtype=np.uint8)

image = np.array([[0, 1, 2],
                  [2, 1, 0],
                  [1, 0, 2]], dtype=np.uint8)


# Color lookup table (LUT) - maps grayscale values to RGB colors
# Suppose 0 -> [255, 0, 0] (red), 1 -> [0, 255, 0] (green), 2 -> [0, 0, 255] (blue)
color_lut = np.array([[255, 0, 0],  # Red for intensity 0
                      [0, 255, 0],  # Green for intensity 1
                      [0, 0, 255]], # Blue for intensity 2
                     dtype=np.uint8)

# Use the grayscale image to index into the LUT
color_image = color_lut[image]

# Resulting RGB image
print(color_image)




[[[255   0   0]
  [  0 255   0]
  [  0   0 255]]

 [[  0   0 255]
  [  0 255   0]
  [255   0   0]]

 [[  0 255   0]
  [255   0   0]
  [  0   0 255]]]


In [10]:
#boolean indexing
#suppose u are working with financial data
data = np.array([100,20,40,400,65,18,26,99,32,29])
condition = data > 50
print(condition)
x = data[condition]
x

[ True False False  True  True False False  True False False]


array([100, 400,  65,  99])

In [16]:
#if u want copy of two rows;
x = np.array([[1,2,3],[7,7,7]])
print(x)

basic = x[:2,:]
print(basic)
print(basic.flags)

advance = x[(0,1),]  #can be list , or better declare variable row = [0,1]
print(advance)
print(advance.flags)

[[1 2 3]
 [7 7 7]]
[[1 2 3]
 [7 7 7]]
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

[[1 2 3]
 [7 7 7]]
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

