In [7]:
#broadcasting: adjusting shape to make operations compatible

#without numpy
a = [[1,2,3],[4,8,9]]
b = [2]
a+b

[[1, 2, 3], [4, 8, 9], 2]

In [8]:
import numpy as np

aa = np.array(a)
bb = np.array(b)
aa+bb  # it broadcasted 2 

#rules of broadcasting:
#corresponding dimension be 1 or equal

array([[ 3,  4,  5],
       [ 6, 10, 11]])

In [14]:
aa = np.arange(3*4).reshape(3,4)
print(aa)
bb = np.array([1,2]) #shape is 1,2 .   3 and 1 will match because its 1, but 4 and 2 mismatch so broad castingf not psossible
#aa + bb error

cc = np.array([1,2,3,-1]) # shape is 1,4   . 3 and 1 will match because its 1, and 4 and 4 willl match becuase same
print(cc)
aa + cc

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 1  2  3 -1]


array([[ 1,  3,  5,  2],
       [ 5,  7,  9,  6],
       [ 9, 11, 13, 10]])